from pathlib import Path

class ReportManager:
    def __init__(self, output_dir: Path)->None:
        self.output_dir=output_dir

    def generate(self, environment:str, version:str, tenant:str, results:list[dict])->None:
        total_pages=len(results)
        successful=sum(1 for r in results if r["status"]=="SUCCESS")
        failed=total_pages-successful
        gallery=""
        for result in results:
            badge="#16a34a" if result["status"]=="SUCCESS" else "#dc2626"

            load_time = (
                f"{result['load_time']:.2f} sec"
                if result["load_time"] is not None
                else "N/A"
            )

            screenshot=result.get("screenshot")
            if screenshot:
                image=Path(screenshot)
                rel=(f"{image.parent.name}/{image.name}").replace("\\","/")
                shot=f'<a href="{rel}" target="_blank"><img class="thumbnail" src="{rel}"></a>'
            else:
                shot='<div class="thumbnail-placeholder">No Screenshot Available</div>'
            gallery+=f"""
<div class="page-card">
<div class="page-header"><div><div class="page-menu">{result['menu']}</div><div class="page-title">{result['submenu']}</div></div><span class="badge" style="background:{badge};">{result['status']}</span></div>
<div class="page-info"><div><strong>Navigation</strong><br>{result['navigation_type']}</div><div><strong>Load Time</strong><br>{load_time}</div></div>
{shot}
</div>"""
        html=f"""<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
*{{box-sizing:border-box}}body{{margin:0;background:#f3f4f6;font-family:Arial}}.header{{background:#fff;padding:30px}}.summary{{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:20px;padding:30px}}.summary-card,.page-card{{background:#fff;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,.08);padding:20px}}.gallery{{display:grid;grid-template-columns:repeat(auto-fill,minmax(420px,1fr));gap:24px;padding:30px}}.page-header{{display:flex;justify-content:space-between}}.thumbnail{{width:100%}}.thumbnail-placeholder{{height:260px;display:flex;align-items:center;justify-content:center;background:#f5f5f5}}.badge{{color:#fff;padding:6px 12px;border-radius:20px}}.footer{{text-align:center;padding:40px}}
</style></head><body>
<div class="header"><h1>VisionQA</h1><p>Visual Regression Report</p></div>
<div class="summary">
<div class="summary-card"><b>Environment</b><br>{environment}</div>
<div class="summary-card"><b>Version</b><br>{version}</div>
<div class="summary-card"><b>Tenant</b><br>{tenant}</div>
<div class="summary-card"><b>Pages</b><br>{total_pages}</div>
<div class="summary-card"><b>Passed</b><br>{successful}</div>
<div class="summary-card"><b>Failed</b><br>{failed}</div>
</div>
<h2 style="padding:0 30px">Screenshot Gallery</h2>
<div class="gallery">{gallery}</div>
<div class="footer">Generated by VisionQA</div>
</body></html>"""
        (self.output_dir/"report.html").write_text(html,encoding="utf-8")
